// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADWnzlLozjKvSXC5E6uVqUNg-MD53R62s',
    appId: '1:626711864650:web:b73d33101645a4b8628db3',
    messagingSenderId: '626711864650',
    projectId: 'student-tracker-2645a',
    authDomain: 'student-tracker-2645a.firebaseapp.com',
    storageBucket: 'student-tracker-2645a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFmYLL_xVXaa8i46g21wSlV3XueXT7Mro',
    appId: '1:626711864650:android:97a7fef9fab6bc0f628db3',
    messagingSenderId: '626711864650',
    projectId: 'student-tracker-2645a',
    storageBucket: 'student-tracker-2645a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW_F3VYq4sseCMS7hBB7mRGxmTVQ8kJiA',
    appId: '1:626711864650:ios:5f80159c5fd72848628db3',
    messagingSenderId: '626711864650',
    projectId: 'student-tracker-2645a',
    storageBucket: 'student-tracker-2645a.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW_F3VYq4sseCMS7hBB7mRGxmTVQ8kJiA',
    appId: '1:626711864650:ios:5f80159c5fd72848628db3',
    messagingSenderId: '626711864650',
    projectId: 'student-tracker-2645a',
    storageBucket: 'student-tracker-2645a.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );
}
